### ISSUE TITLE
Ship list 1.0.0 stable

### ISSUE THREAD

**Issue by Abbe98** [Abbe98/Facile-Framework#11]
## CSS:

- [x] alerts #16
- [x] grid(fluid) #3 #14  
- [x] badges
- [x] buttons #8 #13 
- [x] reset #12 #15 
- [x] code
- [x] help classes #10 
- [x] icons
- [x] labels
- [x] links #4 
- [x] responsive help classes #7 #17
-  [x] tables
- [x] typography
- [x] forms #6 
- [x] menus(navbars) #5 #19 
- [x] print help classes

## Docs/gh-page/Meta
- [ ] basic docs #9 
- [ ] colorkit LESS file
 

## All Issues:
- [x] #1
- [x] #2 
- [x] #3 
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #7 
- [x] #8 
- [ ] #9 
- [x] #10 
- [x] #12 
- [x] #13 
- [x] #14 
- [x] #15 
- [x] #16 
- [x] #17 
- [x] #19
